// swift-tools-version:6.2
// Generated by scripts/lib_publish/publish-libraries.py. Do not edit by hand.
import PackageDescription

let package = Package(
    name: "moot-semantics",
    platforms: [
        .macOS(.v26),
        .iOS(.v26),
    ],
    products: [
        .library(name: "AriaLexiconLib", targets: ["AriaLexiconLib"]),
        .library(name: "EideticLib", targets: ["EideticLib"]),
        .library(name: "LatticeLib", targets: ["LatticeLib"])
    ],
    dependencies: [
        .package(url: "https://github.com/codedaptive/moot-core.git", branch: "main")
    ],
    targets: [
        .target(
            name: "AriaLexiconLib",
            path: "packages/libs/AriaLexiconLib/Sources/AriaLexiconLib"
        ),
        .testTarget(
            name: "AriaLexiconLibTests",
            dependencies: ["AriaLexiconLib"],
            path: "packages/libs/AriaLexiconLib/Tests/AriaLexiconLibTests"
        ),
        .target(
            name: "EideticLib",
            dependencies: ["LatticeLib"],
            path: "packages/libs/EideticLib/Sources/EideticLib",
            resources: [.process("Resources")]
        ),
        .testTarget(
            name: "EideticLibTests",
            dependencies: ["EideticLib", "LatticeLib"],
            path: "packages/libs/EideticLib/Tests/EideticLibTests",
            resources: [.copy("../SharedVectors")]
        ),
        .target(
            name: "LatticeLib",
            dependencies: [.product(name: "SubstrateML", package: "moot-core")],
            path: "packages/libs/LatticeLib/Sources/LatticeLib",
            resources: [.process("Resources")]
        ),
        .testTarget(
            name: "LatticeLibTests",
            dependencies: ["LatticeLib"],
            path: "packages/libs/LatticeLib/Tests/LatticeLibTests"
        )
    ]
)
